# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QRichDem
                                 A QGIS plugin
 Qgis wrappers for RichDem
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-09-22
        copyright            : (C) 2022 by Fee
        email                : freakyfee@proton.me
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = "Fee"
__date__ = "2022-09-22"
__copyright__ = "(C) 2022 by Fee"


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QRichDem class from file QRichDem.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .core.qgis_richdem import QRichDemPlugin

    return QRichDemPlugin()
